
 ######  ##     ##    ###    ########  ######## ######## ########   ######  
##    ## ##     ##   ## ##   ##     ##    ##    ##       ##     ## ##    ## 
##       ##     ##  ##   ##  ##     ##    ##    ##       ##     ## ##       
##       ######### ##     ## ########     ##    ######   ########   ######  
##       ##     ## ######### ##           ##    ##       ##   ##         ## 
##    ## ##     ## ##     ## ##           ##    ##       ##    ##  ##    ## 
 ######  ##     ## ##     ## ##           ##    ######## ##     ##  ######  

define SpecialActions = {
    'Promise_HELP_LS':'A Promise to an Old Friend'
}


 ######  ##     ##    ###    ########     ###     ######  ######## ######## ########  
##    ## ##     ##   ## ##   ##     ##   ## ##   ##    ##    ##    ##       ##     ## 
##       ##     ##  ##   ##  ##     ##  ##   ##  ##          ##    ##       ##     ## 
##       ######### ##     ## ########  ##     ## ##          ##    ######   ########  
##       ##     ## ######### ##   ##   ######### ##          ##    ##       ##   ##   
##    ## ##     ## ##     ## ##    ##  ##     ## ##    ##    ##    ##       ##    ##  
 ######  ##     ## ##     ## ##     ## ##     ##  ######     ##    ######## ##     ##
define IdeologyNames = {
    'fascism':__('Fascism'),
    'communism':__('Communism'),
    'anarchism':__('Anarchism'),
    'conservatism':__('Conservatism'),
    'coporatism':__('Corporatism'),
    'liberalism':__('Liberalism'),
    'libertarianism':__('Libertarianism'),
    'nationalism':__('Nationalism'),
    'progressivism':__('Progressivism')
} 
define IdeologyDesc = {
    'fascism':__(""),
    'communism':__(""),
    'anarchism':__(""),
    'conservatism':__(""),
    'coporatism':__(""),
    'liberalism':__(""),
    'libertarianism':__(""),
    'nationalism':__(""),
    'progressivism':__("")
}
define SkillsetDictionary = {
    'authority':__('Authority'),
    'composure':__('Composure'),
    'conceptualization':__('Abstract Comprehension'),
    'determination':__('Will-Power'),
    'dexterity':__('Dexterity'),
    'empathy':__('Empathy'),
    'encyclopedia':__('Schema'),
    'endurance':__('Endurance'),
    'faith':__('Faith'),
    'focus':__('Focus'),
    'influence':__('Social Influence'),
    'judgement':__('Judgement'),
    'logic':__('Logic'),
    'luck':__('Luck'),
    'perception':__('Sensory Perception'),
    'predatoryinstinct':__('Predatory Conscious'),
    'psychethreshhold':__('Mental Tolerance'),
    'rhetoric':__('Rhetorics'),
    'reaction':__('Reaction'),
    'strength':__('Physical Strength'),
    'vice':__('Vice'),
    'vigor':__('Vigor'),
    'visualcomprehension':__('Visual Comprehension')
}
define SkillAddon = {
    'hedonism':'Hedonistic Calculus'
}

define SkillsetDescDictionary = {
    'authority':__('Make people obey, use order, use force, use your voice. Use your power.'),
    'composure':__('Stand up straight. Don\'t let your spine bend. Have discipline and manner.'),
    'conceptualization':__('Coordinate your thoughts and ideas. Internalize raw information from the world.'),
    'determination':__('Use your will-power to achieve your ambitions. Find something to live for or die for.'),
    'dexterity':__('The pen is mighter than the sword. Or is it? Use your hands to forge your destiny.'),
    'empathy':__('Step into different perspectives, understand people, use it against them or help them.'),
    'encyclopedia':__('Know more about your world and let it guide you. Don\'t let ignorance eat you.'),
    'endurance':__('When you need to run you\'ll need to keep running. Willpower alone doesn\'t keep your heart pumping.'),
    'faith':__('Have hope, have belief, have something to cling on to when your mind will slip and your light will get lost.'),
    'focus':__('Internalize yourself and discover yourself, you\'re a mystery. It shouldn\'t be like that.'),
    'influence':__('Understand high society. Learn the hive mind of artisocracy, corruption and nobility. Be a snake.'),
    'judgement': __('Make and form opinions, let your mind use heurestics and learn from your past. Choices branch your future.'),
    'logic':__('Analyse and structure the world around you into numbers and puzzle pieces that augment and support fundamental reality.'),
    'luck':__('Let oppurutunity take the steering wheel of your destiny and boost your chances of success at whatever you desire.'),
    'perception':__('Be empirical. Experience your world through your limited inputs of reality and the limits of biology. Absorb information form your environment.'),
    'predatoryinstinct':__('Tune in to your animal instincts. Be cautious and hunt your prey. Watch your back and survive. Make reality your favor.'),
    'psychethreshhold':__('Don\'t go insane. Let your mind tolerate whatever the world throws at you and stay within our reality. Don\'t let illusions guide you.'),
    'rhetoric':__('Your voice, your words are our strength. Pave your desires with your tongue and bend the will of others through a vocal sword.'),
    'reaction':__('Have a response to a natural prompt from the entropy of reality. Be prepared to take action to a stimulation. Be quick.'),
    'strength':__('Force your body to go past its limits, stand in the way of an unstoppable force or be the force and take charge.'),
    'vice':__('Let your human desires take control. Give your body its pleasures and relax from discipline. Explore the wild side of life.'),
    'vigor':__('Resist. N/A'),
    'visualcomprehension':__('Don\'t lose yourself to the dark and the ignorance. Use your eyes to extract secrets in plain sight.')
}
#### ##    ## ##     ## ######## ##    ## ########  #######  ########  ##    ## 
 ##  ###   ## ##     ## ##       ###   ##    ##    ##     ## ##     ##  ##  ##  
 ##  ####  ## ##     ## ##       ####  ##    ##    ##     ## ##     ##   ####   
 ##  ## ## ## ##     ## ######   ## ## ##    ##    ##     ## ########     ##    
 ##  ##  ####  ##   ##  ##       ##  ####    ##    ##     ## ##   ##      ##    
 ##  ##   ###   ## ##   ##       ##   ###    ##    ##     ## ##    ##     ##    
#### ##    ##    ###    ######## ##    ##    ##     #######  ##     ##    ##    
define InventoryDescDictionary = {
    'Jade Amulet':__('An Amulet made of Jade. It\'s precious and pricey and easy to carry around. Beautiful green and serene. This is what hope feels like.')
}
##     ##    ###    ########  ########  #### ##    ##  ######   
###   ###   ## ##   ##     ## ##     ##  ##  ###   ## ##    ##  
#### ####  ##   ##  ##     ## ##     ##  ##  ####  ## ##        
## ### ## ##     ## ########  ########   ##  ## ## ## ##   #### 
##     ## ######### ##        ##         ##  ##  #### ##    ##  
##     ## ##     ## ##        ##         ##  ##   ### ##    ##  
##     ## ##     ## ##        ##        #### ##    ##  ######  
# '''
# No Need to bound these for translations since they won't be shown in other languages.
# ''' 
define RomanizedMap = {
    'Kwangchow':'Guangzhou',
    'Hong Kong':'Xiang Gang',
    'Macau':'Aomen',
    'Kwang-Chow Wan':'Guangzhou wan',
    'Shanghai':'Shanghai',
    'Nanking':'Nanjing',
    'Yulin':'Yulin',
    'Foochow':'Fuzhou',
    'Ning-Po':'Ningbo',
    'Nan-Kang':'Nankang',
    'An-King':'Anqing',
    'Tientsin':'Tianjin',
    'Tsingtao':'Qingdao',
    'Wei-Hai-Wei':'Wei-Hai',
    'Da-ren':'Dalian',
    'Peiping':'Beijing',
    'Soochow':'Suzhou',
    'Tai Ping':'Tai Ping',
    'Chang Chow':'Zhangzhou',
    'Sian':'Xi\'an',
    'Kaohshiung':'Gaoxiong',
    'Taipei':'Taibei',
    'Mukden':'Shenyang',
    'Yantai':'Yantai',
    'Weifang':'Weifang',
    'Lini':'Linyi',
    'Tsining':'Jining',
    'Paoting':'Baoding',
    'Yancheng':'Yancheng',
    'Shihkiachwuang':'Shijiazhuang',
    'Lianyun':'Lianyun Gang', 
    'Taichow':'Taizhou',
    'Wenchow':'Wenzhou',
    'Tungkuan':'Dongguan',
    'Yuengkong':'Yangjiang',
    'Swabue':'Shanwei',
    'Kian':'Ji\'an',
    'Kingwha':'Jinhua',
    'Shangkiu':'Shangqiu',
    'Nanyang':'Nanyang',
    'Taiyuan':'Taiyuan',
    'Linfen':'Linfen',
    'Tatung':'Datong',
    'Siangyang':'Xiangyang',
    'Siaokan':'Xiaogan',
    'Yicheng':'Yicheng',
    'Hengyang':'Hengyang',
    'Hwaihwa':'Huaihua',
    'Hochi':'Hechi',
    'kweikang':'Guigang',
    'Pakhoi':'Beihai',
    'Tsunyi':'Zunyi',
    'Luchow':'Luzhou',
    'Bachung':'Bazhong',
    'Fusze':'Yan\'an',
    'Ordos':'Ordos',
    'Bayan Nur':'Bayan Nur',
    'Yuchwan':'Yinchuan',
    'Axla':'Axla',
    'Tenshui':'Tianshui',
    'Lanchow':'Lanzhou',
    'Wuwei':'Wuwei',
    'Kiuquan':'Jiuquan',
    'Deqen':'Deqen',
    'Puerh':'Pu\'er',
    'Chinchew':'Quanzhou',
    'Sanming':'Sanming',
    'Chinwangtao':'Qinhuangdao',
    'Hulutao':'Huludao',
    'Yingkow':'Yingkou',
    'Chaoyang':'Chaoyang',
    'Chihfeng':'Chifeng',
    'Hsinking':'Changchun',
    'Tungliao':'Tongliao',
    'Hulun Buir':'Hulun Buir',
    'Manchowli':'Manzhou-li',
    'Tsitsihar':'Tsitsihar',
    'Kiamusze':'Jiamuzi',
    'Mutankiang':'Mudanjiang',
    'Kashgar':'Kashgar',
    'Karamay':'Karamay',
    'Altay':'Altay',
    'Urumqi':'Urumqi',
    'Bayingol':'Bayingol',
    'Kumul':'Kumul',
    'Nagqu':'Nagqu',
    'Kalgan':'Kalgan',
    'Chaochow':'Chaozhou',
    'Chengtu':'Chengdu',
    'Kwuangyun':'Guangyuan',
    'Hsilin Gol':'Xilin Gol',
    'Aba':'Aba',
    'Leshan':'Leshan',
    'Garze':'Garze',
    'Tongren':'Tongren',
    'Kingchow':'Jingzhou',
    'Ankang':'Ankang',
    'Shiyan':'Shiyan',
    'Qamdo':'Qamdo',
    'Shiukwan':'Shaoguan',
    'Kanchow':'Ganzhou',
    'Wu-Hsi':'Wu-xi'
}
define RomanizedPinyinMap = {
    'Kwangchow':'Guǎngzhōu',
    'Hong Kong':'Xiāng gǎng',
    'Macau':'Àomén',
    'Kwang-Chow Wan':'Guǎngzhōu wān',
    'Shanghai':'Shànghǎi',
    'Nanking':'Nánjīng',
    'Yulin':'Yùlín',
    'Foochow':'Fúzhōu',
    'Ning-Po':'Níngbō',
    'Nan-Kang':'Nankang',
    'An-King':'Ānqìng',
    'Tientsin':'Tiānjīn',
    'Tsingtao':'Qīngdǎo',
    'Wei-Hai-Wei':'Wēihǎi',
    'Da-ren':'Dàlián',
    'Peiping':'Běijīng',
    'Soochow':'Sūzhōu',
    'Tai Ping':'Tài píng',
    'Chang Chow':'Zhāngzhōu',
    'Sian':'Xī\'ān',
    'Kaohshiung':'Gāoxióng',
    'Taipei':'Táiběi',
    'Mukden':'Shěnyáng',
    'Yantai':'Yāntái',
    'Weifang':'Wéifāng',
    'Lini':'Línyí',
    'Tsining':'Jìníng',
    'Paoting':'Bǎodìng',
    'Yancheng':'Yánchéng',
    'Shihkiachwuang':'Shíjiāzhuāng',
    'Lianyun':'Liányún Gǎng',
    'Taichow':'Táizhōu',
    'Wenchow':'Wēnzhōu',
    'Tungkuan':'Dōngguǎn',
    'Yuengkong':'Yángjiāng',
    'Swabue':'Shànwěi',
    'Kian':'Jí\'ān',
    'Kingwha':'Jīnhuá',
    'Shangkiu':'Shāngqiū',
    'Nanyang':'Nányáng',
    'Taiyuan':'Tàiyuán',
    'Linfen':'Línfén',
    'Tatung':'Dàtóng',
    'Siangyang':'Xiāngyáng',
    'Siaokan':'Xiàogǎn',
    'Yicheng':'Yíchéng',
    'Hengyang':'Héngyáng',
    'Hwaihwa':'Huáihuà',
    'Hochi':'Héchí',
    'kweikang':'Guìgǎng',
    'Pakhoi':'Běihǎi',
    'Tsunyi':'Zūnyì',
    'Luchow':'Lúzhōu',
    'Bachung':'Bā-Zhōng',
    'Fusze':'Yán\'ān',
    'Ordos':'Ordos',
    'Bayan Nur':'Bayan Nur',
    'Yuchwan':'Yínchuān',
    'Axla':'Axla',
    'Tenshui':'Tiānshuǐ',
    'Lanchow':'Lánzhōu',
    'Wuwei':'Wǔwēi',
    'Kiuquan':'Jiǔquán',
    'Deqen':'Deqen',
    'Puerh':'Pǔ\'ěr',
    'Chinchew':'Quánzhōu',
    'Sanming':'Sānmíng',
    'Chinwangtao':'Qínhuángdǎo',
    'Hulutao':'Húlu dǎo',
    'Yingkow':'Yíngkǒu',
    'Chaoyang':'Chāoyáng',
    'Chihfeng':'Chìfēng',
    'Hsinking':'Chǎngchūn',
    'Tungliao':'Tóngliáo',
    'Hulun Buir':'Hulun Buir',
    'Manchowli':'Mǎnzhōulǐ',
    'Tsitsihar':'Tsitsihar',
    'Kiamusze':'Jiāmùsī',
    'Mutankiang':'Mǔdānjiāng',
    'Kashgar':'Kashgar',
    'Karamay':'Karamay',
    'Altay':'Altay',
    'Urumqi':'Urumqi',
    'Bayingol':'Bayingol',
    'Kumul':'Kumul',
    'Nagqu':'Nagqu',
    'Kalgan':'Kalgan',
    'Chaochow':'Chào-Chōu',
    'Chengtu':'Chéngdū',
    'Kwuangyun':'Guǎngyuán',
    'Hsilin Gol':'Xilin Gol',
    'Aba':'Aba',
    'Leshan':'Leshan',
    'Garze':'Garze',
    'Tongren':'Tóngrén',
    'Kingchow':'Jīngzhōu',
    'Ankang':'Ānkāng',
    'Shiyan':'Shíyàn',
    'Qamdo':'Qamdo',
    'Shiukwan':'Sháoguān',
    'Kanchow':'Gànzhōu',
    'Wu-Hsi':'Wúxī'
}
define LeaderRomanize = {
    'Chiang Chieh Shih':'Jiang JieShi',
    'Mao Tse-Tung':'Mao ZeDong',
    'Emperor Hirohito':'Emperor Hirohito',
    'Aisin Gioro Pu-Yi':'Ai Xin Jue Luo Pu-Yi',
    'Wang Ching-Wei':'Wang Jing-Wei',
    'Yin-Ju-Keng':'Yin Ru-Geng',
    'Prince Demchugdongrub':'Prince Demçigdonrob',
    'Sung Che-Yuan':'Song Zheyuan',
    'Yan HsiShan':'Yan Xi-Shan',
    'Ma Bu Fang':'Ma Bu-Fang',
    'Li Tsung-Jen':'Li Zongren',
    'Lung Yun':'Long Yun',
    'Han Fuchu':'Han Fuju',
    'Chang Chih Chung':'Zhang ZhiZhong',
    'Liu Hsiang':'Liu Xiang',
    'Liu Wen Hui':'Liu Wen-Hui',
    'ShengShih Ts\'ai':'Sheng Shi-Cai',
    'Jamphel Yeshe Gyaltsen':'Jamphel Yeshe Gyaltsen',
    'Elihan Tore':'Elihan Tore',
    'Li Mi':'Li Mi',
    'Ngolok Tribes':'Ngolok Tribes',
    'Kim Il-Sung':'Kim Il-Sung',
    'Archibald Vincent Arnold':'Archibald Vincent Arnold',
    'Neville Chamberlain':'Neville Chamberlain',
    'Antonio de Oliveira Salazar':'Antonio de Oliveira Salazar',
    'Camille Chautemps':'Camille Chautemps',
    'Joseph Stalin':'Iosif Stalin',
    'Franklin D Roosevelt':'Franklin D Roosevelt'
}
define LeaderPinyinRomanize = {
    'Chiang Chie Shih':'Jiǎng JièShí',
    'Mao Tse-Tung':'Máo ZéDōng',
    'Emperor Hirohito':'Emperor Hirohito',
    'Aisin Gioro Pu-Yi':'Ài-Xīn Jué-Luó Pǔ-Yí',
    'Wang Ching-Wei':'Wāng Jīng-Wèi',
    'Yin-Ju-Keng':'Yīn Rǔ-Gēng',
    'Prince Demchugdongrub':'Prince Demchigdonrov',
    'Sung Che-Yuan':'Sòng Zhé-Yuán',
    'Yan HsiShan':'Yán Xī-Shān',
    'Ma Bu Fang':' Mǎ Bùfāng',
    'Li Tsung-Jen':'Lǐ Zōngrén',
    'Lung Yun':'Lóng Yún',
    'Han Fuchu':'Hán Fùjǔ',
    'Chang Chih Chung':'Zhāng Zhìzhōng',
    'Liu Hsiang':'Liú xiāng',
    'Liu Wen Hui':'Liú Wénhuī;',
    'ShengShih Ts\'ai':'Shèng Shìcái',
    'Jamphel Yeshe Gyaltsen':'Jamphel Yeshe Gyaltsen',
    'Elihan Tore':'Elihan Tore',
    'Li Mi':'Lǐ Mí',
    'Ngolok Tribes':'Ngolok Tribes',
    'Kim Il-Sung':'Kim Il-Seong',
    'Archibald Vincent Arnold':'Archibald Vincent Arnold',
    'Neville Chamberlain':'Neville Chamberlain',
    'Antonio de Oliveira Salazar':'António de Oliveira Salazar',
    'Camille Chautemps':'Camille Chautemps',
    'Joseph Stalin':'Iósif Stálin',
    'Franklin D Roosevelt':'Franklin D Roosevelt'
}
define NationDescDictionary = {
    'CHI-1937_desc':__('The Republic of China was established on Janurary 1st 1912 after the Xinhai Revolution which overthrew the Qing dynasty. It was de-facto dissolved during the warlord era until in 1921 the Kuomintang established a rival government in Canton. Chiang Chieh Shih who came into power through a military coup began a northern expedition to capture cities fro warlords and proclaim a central government to unite China under. Many foreign nations recognised the Nationalist government as the legitimate unified government of China, even the Soviet Union which supported the Chinese communists. After the Nanjing decades of the 1930s the Republic was weak and thrown into constant war of unification and resistance against foreign powers such as Japan.'),
    'PRC-1937_desc':__('The communists knew aafter the 1927 Shanghai massacre that anywhere under nationalist rule was not their home anymore. They retreated and began to cross rivers and mountains and set up a base in Shanxi to try and regroup. It seemed hope was not on their side especially at the brink of a full out war. The great march has finished and only a fraction of the red army remains at their last stand in Shanxi. After three failed Kuomintang encirclements and a respite after the Sian incident in 1936 the Chinese Soviet Republic has to keep itself together and face the adversities of foreign aggression and imperialism. Left with a barely standing army decisions have to be made and people have to join the fight to protect the sovereignty of China.'),
    'JAP-1937_desc':__('Three quarters of a century have passed since the establishement of a modern empire in the east. The code of Bushido and a sense of unity has finally left Japan strong and resistant to western imperialism in Asia. They kept building ships and producing guns for foreign conquests in Korea and North East China and exploiting people and resources in the dire times of the great depression. The empire now stands at crossroads after choosing the military and supressing the Kodoha coup in 1936 which lead to end of the government assassination period and a new future to an empire where the sun never sets. Japan\'s eyes are now on China\'s resources and weak military and see no reason to take what feels it rightfully theres. For the Emperor! Banzai!'),
    'MAN-1937_desc':__('Manchukuo was set up by the Japanese to give legitimacy to their occupation of North East China. An area of rich industrial strength allowed Japan to grow their strength and look at the future. Emperor Aisin Gioro Pu-Yi sits on his consolation throne and dreams of the Qing returning and flying the flag of the dragon once again. Pressed under the thumb of the militant Japanese and the autonomous Kwantung army and facing beligerancy from bandits and anti-Japanese resistance Manchukuo must juggle the responsbilities of a unwanted monarchy in a chaotic time period. The flag of Manchukuo unites the 5 races under the one hand of Pu-Yi and extends it out to reclaim what it rightfully owns. Manchukuo will rise and unshackle itself.'),
    'RNG-1937_desc':__(''),
    'EHA-1937_desc':__(''),
    'MEN-1937_desc':__('The Mongol Military Government as it is called now, only popped into existence after Mongolian elites decided to favour Japan over the central government. The newly formed government consists of a nomadic population and only two provinces in a sparsely and frankly deserted place. Acting as a buffer for the Shaanxi warlord the Hebei-Chahar political council the newly formed nation was formed through betrayal and treason. Prince Demchugdongrub now observes the Mongol Military Government and visions a better future for Mongolia and his fellow subjects who have been dominated by the imperialism of other nations such as the USSR and China. It\'s time to team up with Japan and free their people from imperialism once and for all. Uukhai!'),
    'PGR-1937_desc':__('The Hopeh Chahar Political Council was born in 1935 after Japan forced China\'s hand in the He Umezu Agreement as an attempt to end Kuomintang Influence in the Northern most provinces bordering Manchukuo and Mengkukuo. In reality the council gave lip service to the Japanese and cooperated with the Kuomintang central government. The Japanese set up the their own government in the region in East Hopeh while a majority of territory was allocated to the council. The goal to secure the 5 most northern provinces failed and forced the Japanese back on their plans for domination in China. Now the council has to choose it\'s path and stand up to Japanese aggression in Northern China.'),
    'SHX-1937_desc':__('Shanxi Clique has been around since the 1911 Xinhai revolution and has been steady in its political and economic interests. Shanxi is a target of many desperate invaders including the Japanese, Kuomintang and the communists as part of securing northern China. Lagre iron deposits and soldier farmers roam the vast land of Shanxi as one million peasant farmers and labourers are becoming introduced the the marxist theories from the Yan\'an communists. In 1936 Shanxi stood its ground against the Manchukuo and Japanese forces wishing to reunify Suiyuan under Mengkukuo by forcing military training and conscription for all students and formed an informal alliance with the communists to fend off the land grabbers of Dongbei. Where will Shanxi go? The world wonders.'),
    'XSM-1937_desc':__('The Ma Clique is the North West warlord state that is run by \"The Three Ma\'s\". A steady and self sufficient state in which progress is focussed on living standards than war. Hsi-Pei San Ma still has conflicts with the tibetans and Ngolok that wish to take back their lands and have defended themselves throughly enough to take more land from Tibet. Fear of communism was so strong with the Ma Clique that genocide and systematic extermination against Ngolok tribes got more and more often and much more violent and brutal. A majority Islamic nation with a majority Hui Chinese population Hsi-Pei San Ma preserve their autonomy and authority with an iron fist and look forward to the future with a looming war with Japan.'),
    'GXC-1937_desc':__(''),
    'YUN-1937_desc':__(''),
    'SDC-1937_desc':__(''),
    'HNC-1937_desc':__(''),
    'SHC-1937_desc':__(''),
    'SKC-1937_desc':__(''),
    'SIK-1937_desc':__(''),
    'TIB-1937_desc':__('Tibet is one of the Turkic nations alongside the Mongolian hegemony that wishes to assert the will of their people to self determination. It has been only one year since the birth of Tenzin Gyatso who was reincarnated from Thubten Gyatso and Tibet is overjoyed with the prospect of the arrival of the 14th Dalai Lama. Tibet as of now is vulnerable to the creeping influence of the Central Nationalist Government and the encroaching British from the British Raj who were looking to expand their borders. Tibet now like Mongolia wishes to assert its nationhood in the international community. Tibet as of now is fractured and difficult to unify due to its nomadic population but will persist in their struggle.'),
    'ETR-1937_desc':__(''),
    'BKT-1937_desc':__(''),
    'KII-1937_desc':__(''),
    'KON-1937_desc':__(''),
    'DRK-1937_desc':__(''),
    'KOR-1937_desc':__(''),
    'ENG-1937_desc':__(''),
    'POR-1937_desc':__(''),
    'FRA-1937_desc':__(''),
    'SOV-1937_desc':__('The Molotov-Ribbentrop Pact guaranteed security. It seems that Hitler\'s ambitions in Europe will keep on growing and Soviet requirement to increase defence capability is important. Two Anti-Comintern pact members are now sizing up the borders of the USSR. A ultra-nationalist Germany in the west which will flatten land up to Moscow and a beligerant Japan in the East expecting a second Russo-Japanese war and a hefy territory to conquer. The Soviet Union now paranoid and in chaos has purged hope literally and figuretively as Stalin\'s paranoia grows. The USSR will arm themselves under their flag and fight for their motherland. They will sing glories of the defence of the motherland. Our men will follow order 255: Not One Step Back!'),
    'USA-1937_desc':__('')
}
define CityDesc = {
    'Nanking':"Nanjing is the capital of the Republic of China."
}