label Beijing_chapter_one_Day2_8_9_1937:
"The blurred sounds merge like a bucket of different paints."
"I can't event tell if my eyes are open or closed."
"I try to adjust my eyes again."
"It's dark and there aren't any silhouette's even."
Gh "We're nearing Tientsin."
"Guo Heng had been awake for some time."
"Crouching near a box of liquor with a thin carpet as a blanket."
if fang.randomise_compare("empathy", 2,4):
    empathy neutral "He seems cold."
    empathy neutral "He let you two have the warm ones."
    empathy neutral "Wanna return the favour?"
    logic neutral "He might be able to handle it... can you?"
    logic neutral "Pay attention to health."
    menu:
        "Give Guo Heng your blanket":
            pass
        "Keep the warm blanket for yourself":
            pass
Gh "Pretty much whatever is left of Hsi-Ku arsenal."
Mw "They turned that place into a school didn't they?"
Gh "Yeah."
Mw "That arsenal would be really handy right now."
Dy "They're already scuffling I bet."
Dy "Lord knows what's going to be the outcome."
Dy "My boss hasn't told me a course of action yet so I continue my job today until I meet him in Shanghai."
Gh "How long will this take?"
Gh "5 minutes if all hands are on deck."
if fang.randomise_compare("rhetoric", 4,5):
    rhetoric neutral "This will get done faster if you help out."
    rhetoric neutral "I don't want to be here too."
"Ma Wen rolled his eyes."
"We began to crawl out of the back and lined up with goods."
Dy "It's right in this establishment."
"The place was shanty but it was a liquor store."
"There was a dim dying lantern one one side of the building."
"A implied lantern was hanging behind the building as well."
Gh "What are we expecting？"
Dy "A few drunks."
Dy "Pecker up we'll be fine."
"Da-Yu stacked up two grates and heaved them on his chest."
"He walked ahead of us and began to guide us to where to go."
Dy "The old fella that runs this place tells me to dump it in his cellar."
"Da-Yu gently placed the crates on a little stone wall."
"His hands began to pat the patchs of grass near the wall before tugging on a rotten stringy fibres of rope."
Dy "Got it."
"Da-Yu heaved as he pulled up a concrete lid."
Dy "Shit is heavy."
"Guo Heng looked at me worriedly."
Gh "You think this looks fishy?"
"He whispered this to me."
Mw "Even if it is then shut up."
Dy "Let me get a torch."
"Da-Yu jogged back to his truck leaving us to stare at the abyss in the cellar."
Gh "Look like a place to trap people and slave them."
Mw "Wouldn't they have crawled out by now?"
Gh "They could be tied up."
Gh "Besides who uses a disguised concrete lid for a cellar?"
Mw "A business that has to hide stock from dangerous drunks on a daily basis."
Gh "I'm not walking down there."
Gh "I'll stay near the truck."
Mw "I'll take the damn dive."
if Mw.mood == "offended":
    Mw "Not like you will Fang."
    "Ma Wen glared at me."
"Guo Heng put down his crate on the low stone wall and walked back as Da-Yu came back."
Dy "What's up with him?"
Dy "Wants us to keep waiting？"
Mw "He said he was going to unload the crates and Fang will fetch them while I takes them inside."
Dy "Made my job easier."
Dy "Here's the torch by the way."
Dy "Watch out for stray rats, don't put them at the lowest level cause they get in."
Dy "Last month my lackey got a bad bite."
Dy "Maybe a damn snake?"
"Ma Wen looked at him, a bit shaken."
"Da-Yu burst out laughing."
Dy "I'm kidding. I unload alone, only some damn rats."
"Ma Wen nodded slowly and clutched his crate into his left arm and grabbed the handheld torch."
"He began to descend the cold stairs."
if Mw.mood == "Offended":
    Mw "Fuck this shit."
    "He muttered under his breath."
Gh "Fang!"
"His voice was faint and distant."
"I began to take steps back to the truck."
"Guo Heng looked down at me."
Gh "Here's a crate."
"I took it into my arms and began to move back."
"After 10 minutes of leaving a crate at the mouth of the cellar the work was finished."
Dy "Glad that's over with."
Dy "Let's get going now."
"Ma Wen crawled out of the mouth of the cellar scratching his sculp viciously."
"He dug his nails into the dirt and climbed out."
Dy "Find many rats down there?"
Mw "No."
Dy "The old guy must have hunted them down."
Dy "I heard they fetch good prices in other villages."
Mw "Can we just get going?"
Dy "Sure."
"Guo Heng was already at the truck and we were ready to trek down to Tsingtao."
Gh "We should get some good sleep."
Mw "I agree."
"Ma Wen looked tired and shaken up from the bugs in the cellar."
"For a noble... he had good tolerance."
if fang.randomise_compare("logic", 4,6):
    logic neutral "Why?"
    logic neutral "That is strange isn't it?"
    pred neutral "The world is a harsh place."
    pred neutral "I don't blame him for adjusting to it as it is required."
    logic neutral "Perhaps we are assuming wrongly about how long he has been on his own."
    logic neutral "He could have lied even."
    pred neutral "People have their secrets."
    pred neutral "Watch your back."